from enum import IntEnum

class HeartRate(IntEnum):
    UNKNOWN = 0
    FUNCTION_BLOCK_INFO = 0
    GET_ALL = 1
    HEART_RATE = 2
    HEART_RATE_STATS = 3
    SPEED_AND_DISTANCE = 4
    STEP_RATE_STATS = 5
    CALORIES = 6
    VO2 = 7
    USER_INFO = 8
    WORKOUT_INFO = 9
    HR_READING_RELIABILITY = 10
    OPTICAL_SENSOR_STATUS = 11
    POST_STATUS = 12
    CALIBRATION_INFO = 13
    FIRMWARE_VERSION = 14
    HARDWARE_INFO = 15
